kind: ConfigMap
apiVersion: v1
metadata:
  name: multus-cni-node-config
  namespace: kube-system
data:
  05-multus-cni.conf: |
    {"name": "multus-cni",
     "cniVersion":"0.1.0",
     "type": "multus-cni",
     "kubeconfig": "/etc/kubernetes/kubelet.conf",
     "delegates": [
       __10-calico.conflist__
     ]
    }
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: multus-cni-node
  namespace: kube-system
  labels:
    app: multus-cni-node
spec:
  selector:
    matchLabels:
      app: multus-cni-node
  template:
    metadata:
      labels:
        app: multus-cni-node
    spec:
      tolerations:
      - key: node.kubernetes.io/not-ready
        effect: NoSchedule
      containers:
      - name: cni-node
        image: openvnf/cni-node
        command:
        - cni-node
        - install
        - --plugins=multus-cni,macvlan
        - --configs=05-multus-cni.conf
        - --wait
        lifecycle:
          preStop:
            exec:
              command:
              - cni-node
              - uninstall
              - --plugins=multus-cni,macvlan
              - --configs=05-multus-cni.conf
        volumeMounts:
        - name: kubectl
          mountPath: /bin/kubectl
        - name: cnibin
          mountPath: /host/opt/cni/bin
        - name: cnicfg
          mountPath: /host/etc/cni/net.d
        - name: multus-cni-node-config
          mountPath: /etc/cni/net.d
      volumes:
      - name: kubectl
        hostPath:
          path: /opt/bin/kubectl
      - name: cnibin
        hostPath:
          path: /opt/cni/bin
      - name: cnicfg
        hostPath:
          path: /etc/cni/net.d
      - name: multus-cni-node-config
        configMap:
          name: multus-cni-node-config
