#!/bin/bash

set -e

Usage=$(cat <<EOF
Usage: cni-node <Command> [Options]

Commands
    install    install according to the options
    uninstall  uninstall according to the options
    apply      install and uninstall comparing desired and current items

    list       list available CNI plugins
    version    show version

Options
    --plugins=<Desired[:Current]>    Comma separated CNI plugins
    --configs=<Desired[:Current]>    CNI configuration templates
    --manifests=<Desired[:Current]>  Kubernetes manifest templates
    --pause                          Pause for SIGTERM or SIGINT after the
                                     specified command complete
EOF
)

function main {
    local Action="$1"

    case "${Action}" in
        install|\
        uninstall|\
        apply)
            local Pause=false

            shift
            local Arg
            for Arg in "$@"; do
                case "${Arg}" in
                    --plugins=*) local Plugins="${Arg#*=}" ;;
                    --configs=*) local Configs="${Arg#*=}" ;;
                    --manifests=*) local Manifests="${Arg#*=}" ;;
                    --pause) Pause=true ;;
                    *) unknown_option "${Arg}" ;;
                esac
            done

            cli_do_action "${Action}" plugins "${Plugins}"
            cli_do_action "${Action}" configs "${Configs}"
            cli_do_action "${Action}" manifests "${Manifests}"

            if ${Pause}; then pause; fi
        ;;
        list) ls -1 /opt/cni/bin ;;
        version) cat /cni-node-version ;;
        *) usage ;;
    esac
}

function cli_do_action {
    local Action="$1"
    local Type="$2"
    local Items="$3"
    local Desired="${Items//:*/}"; Desired="${Desired//,/ }"
    local Current="${Items//*:/}"; Current="${Current//,/ }"

    do_action "${Action}" "${Type}" "${Desired}" "${Current}"
}

function do_action {
    local Action="$1"
    local Type="$2"
    local Desired="$3"
    local Current="$4"

    if [ "${Action}" = "apply" ]; then
        local Added
        local Removed

        Added="$(difference added "${Desired}" "${Current}")"
        Removed="$(difference removed "${Desired}" "${Current}")"

        do_action install "${Type}" "${Added}"
        do_action uninstall "${Type}" "${Removed}"

        return
    fi

    if [ "${Action}" = "uninstall" ]; then
        Desired="$(items_reverse "${Desired}")"
    fi

    local Item
    for Item in ${Desired}; do
        "${Type%?}"_"${Action}" "${Item}"
    done

    if [ -n "${Desired}" ]; then
        echo "Done."
    fi
}

function plugin_install {
    local Plugin="$1"
    echo "Installing CNI plugin ${Plugin}..."
    mkdir -p "/host/opt/cni/bin"
    install "/opt/cni/bin/${Plugin}" "/host/opt/cni/bin/${Plugin}"
}
function plugin_uninstall {
    local Plugin="$1"
    echo "Uninstalling CNI plugin ${Plugin}..."
    rm -f "/host/opt/cni/bin/${Plugin}"
}

function config_install {
    local FileName="$1"
    local Content; Content="$(cat "/etc/cni/net.d/${FileName}")"
    local SedArgs; SedArgs="$(sed_args "${Content}")"

    if [ -n "${SedArgs}" ]; then
        Content="$(echo "${Content}" | sed ${SedArgs})"
    fi

    echo "Installing CNI configuration from ${FileName}..."
    echo "### ${FileName} ###"
    echo "${Content}"
    echo "###"

    mkdir -p "/host/etc/cni/net.d"
    echo "${Content}" | tee "/host/etc/cni/net.d/${FileName}" > /dev/null
}
function config_uninstall {
    local FileName="$1"
    echo "Uninstalling CNI configuration ${FileName}..."
    rm -f "/host/etc/cni/net.d/${FileName}"
}

function manifest_install {
    local FileName="$1"
    local Content; Content="$(cat "/etc/kubernetes/manifests/${FileName}")"

    echo "Applying Kubernetes object..."
    echo "### ${FileName} ###"
    echo "${Content}" | envsubst
    echo "###"

    echo "${Content}" | envsubst | kubectl apply --filename -
}
function manifest_uninstall {
    local FileName="$1"
    local Content; Content="$(cat "/etc/kubernetes/manifests/${FileName}")"

    echo "Deleting Kubernetes object..."
    echo "### ${FileName} ###"
    echo "${Content}" | envsubst
    echo "###"

    echo "${Content}" | envsubst | kubectl delete --filename -
}

function sed_args {
    local Content="$1"
    local Pointer
    local Pointers

    Pointers="$(echo "${Content}" | sed -n "s/.*__\\(.*\\)__.*/\\1/p")"
    for Pointer in ${Pointers}; do
        printf %b " -e /__${Pointer}__/r/host/etc/cni/net.d/${Pointer}" \
                  " -e /__${Pointer}__/d"
    done
}

function difference {
    local Condition="$1"
    local Desired="$2"
    local Current="$3"

    case "${Condition}" in
        added) local N=2 ;;
        removed) local N=1 ;;
    esac

    local Diff
    Diff="$(comm -"${N}3" <(echo "${Desired}" | xargs -n1 | sort) \
                          <(echo "${Current}" | xargs -n1 | sort) |
                 paste -sd" " -)"

    case "${Condition}" in
        added) local Target="${Desired}" ;;
        removed) local Target="${Current}" ;;
    esac

    local Result=()
    for Item in ${Target}; do
        if [[ "${Diff}" =~ ${Item} ]]; then
            Result+=("${Item}")
        fi
    done
    echo "${Result[@]}"
}

function items_reverse {
    local Items="$1"
    echo "${Items}" | xargs -n1 | tac | paste -sd" " -
}

function pause {
    echo "Paused (waiting for SIGTERM or SIGINT to stop)..."
    trap stop SIGTERM SIGINT
    while :; do
        sleep 1
    done
}
function stop {
    echo "Stopped."
    exit 0
}

function usage {
    >&2 echo "${Usage}"
    exit 2
}
function unknown_option {
    local Option="$1"
    >&2 echo "Unknown option: ${Option%%=*}"
    exit 2
}

main "$@"
