#!/bin/bash

set -e

USAGE="Usage: cni-node-apply <Type> <Current> <Previous>"

function main {
    local TYPE="$1"
    local CURRENT="${2//,/ }"
    local PREVIOUS="${3//,/ }"
    local TO_INSTALL
    local TO_UNINSTALL

    if [ -z "${TYPE}" ] || [ -z "${CURRENT}" ]; then usage; fi

    TO_INSTALL="$(difference added "${CURRENT}" "${PREVIOUS}")"
    TO_UNINSTALL="$(difference removed "${CURRENT}" "${PREVIOUS}")"

    cni-node install "--${TYPE}=${TO_INSTALL// /,}"
    cni-node uninstall "--${TYPE}=${TO_UNINSTALL// /,}"
}

function difference {
    local CONDITION="$1"
    local CURRENT="$2"
    local PREVIOUS="$3"

    case "${CONDITION}" in
        added) local N=2 ;;
        removed) local N=1 ;;
    esac

    local DIFF
    DIFF="$(comm -"${N}3" <(echo "${CURRENT}" | xargs -n1 | sort) \
                          <(echo "${PREVIOUS}" | xargs -n1 | sort) |
                 paste -sd" " -)"

    case "${CONDITION}" in
        added) local TARGET="${CURRENT}" ;;
        removed) local TARGET="${PREVIOUS}" ;;
    esac

    local RESULT=()
    for ITEM in ${TARGET}; do
        if [[ "${DIFF}" =~ ${ITEM} ]]; then
            RESULT+=("${ITEM}")
        fi
    done
    echo "${RESULT[@]}"
}

function usage {
    >&2 echo "${USAGE}"
    exit 2
}

main "$@"
