#!/bin/sh

set -e

USAGE=$(cat <<EOF
Usage: cni-node <Command> [Options]

Commands
    install    install specified CNI plugins and configuration
    uninstall  uninstall specified CNI plugins and configuration

    list       list available CNI plugins
    version    show version

Options
    --plugins=<Plugins>  Comma separated CNI plugins
    --config=<Template>  CNI configuration template
EOF
)

function main {
    case "$1" in
        install|uninstall)
            local ACTION="$1"
            shift
            for ARG in "$@"; do
                case "${ARG}" in
                    --plugins=*) local PLUGINS="${ARG#*=}"; shift ;;
                    --config=*) local CONFIG="${ARG#*=}"; shift ;;
                    *=*) >&2 echo "Unknown argument: ${ARG%=*}"; exit 2 ;;
                    *) >&2 echo "Unknown argument: ${ARG}"; exit 2 ;;
                esac
            done
            [ -n "${PLUGINS}" ] && "${ACTION}_plugins" "${PLUGINS/,/ }"
            [ -n "${CONFIG}" ] && "${ACTION}_config" "${CONFIG}";
        ;;
        list) ls -1 /opt/cni/bin ;;
        version) cat /version ;;
        *) usage ;;
    esac
}

function install_plugins {
    local PLUGINS=$*

    for PLUGIN in ${PLUGINS}; do
        echo "Installing CNI plugin ${PLUGIN}..."
        install "/opt/cni/bin/${PLUGIN}" "/host/opt/cni/bin/${PLUGIN}"
    done
    echo "Done."
}
function install_config {
    local TEMPLATE="/etc/cni/net.d/$1"

    echo "Installing CNI configuration from $(basename "${TEMPLATE}")..."

    local SED_ARGS; SED_ARGS="$(sed_args "${TEMPLATE}")"
    if [ -n "${SED_ARGS}" ]; then
        sed ${SED_ARGS} "${TEMPLATE}" | tee "/host/${TEMPLATE}" > /dev/null
    else
        cp "${TEMPLATE}" "/host/${TEMPLATE}"
    fi

    echo "### ${TEMPLATE} ###"
    cat "/host/${TEMPLATE}"
    echo "###"
}

function uninstall_plugins {
    local PLUGINS=$*

    for PLUGIN in ${PLUGINS}; do
        echo "Uninstalling CNI plugin ${PLUGIN}..."
        rm -f "/host/opt/cni/bin/${PLUGIN}"
    done
    echo "Done."
}
function uninstall_config {
    local CONFIG="/host/etc/cni/net.d/$1"

    echo "Ununstalling CNI configuration $(basename "${CONFIG}")..."
    rm -f "${CONFIG}"
}

function sed_args {
    local TEMPLATE="$1"

    for POINTER in $(template_pointers "${TEMPLATE}"); do
        printf %b " -e /__${POINTER}__/r/host/etc/cni/net.d/${POINTER}" \
                  " -e /__${POINTER}__/d"
    done
}

function template_pointers {
    local TEMPLATE="$1"
    grep -o "__\\(.*\\)__" "${TEMPLATE}" | sed "s/__\\(.*\\)__/\\1/"
}

function usage {
    >&2 echo "${USAGE}"
    exit 2
}

main "$@"
